// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: purchase/purchase.proto
// Protobuf Java Version: 4.34.1

package com.example.grpc.purchase;

@com.google.protobuf.Generated
public interface AddToCartGrpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:purchase.AddToCartGrpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
