// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: purchase/purchase.proto
// Protobuf Java Version: 4.34.1

package com.example.grpc.purchase;

/**
 * Protobuf type {@code purchase.CheckoutGrpcRequest}
 */
@com.google.protobuf.Generated
public final class CheckoutGrpcRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:purchase.CheckoutGrpcRequest)
    CheckoutGrpcRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "CheckoutGrpcRequest");
  }
  // Use CheckoutGrpcRequest.newBuilder() to construct.
  private CheckoutGrpcRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CheckoutGrpcRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.purchase.PurchaseProto.internal_static_purchase_CheckoutGrpcRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.example.grpc.purchase.PurchaseProto.internal_static_purchase_CheckoutGrpcRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.purchase.PurchaseProto.internal_static_purchase_CheckoutGrpcRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.purchase.CheckoutGrpcRequest.class, com.example.grpc.purchase.CheckoutGrpcRequest.Builder.class);
  }

  public static final int TOURIST_ID_FIELD_NUMBER = 1;
  private long touristId_ = 0L;
  /**
   * <code>int64 tourist_id = 1;</code>
   * @return The touristId.
   */
  @java.lang.Override
  public long getTouristId() {
    return touristId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (touristId_ != 0L) {
      output.writeInt64(1, touristId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (touristId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, touristId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.purchase.CheckoutGrpcRequest)) {
      return super.equals(obj);
    }
    com.example.grpc.purchase.CheckoutGrpcRequest other = (com.example.grpc.purchase.CheckoutGrpcRequest) obj;

    if (getTouristId()
        != other.getTouristId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOURIST_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTouristId());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.purchase.CheckoutGrpcRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.purchase.CheckoutGrpcRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.purchase.CheckoutGrpcRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.purchase.CheckoutGrpcRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.purchase.CheckoutGrpcRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.purchase.CheckoutGrpcRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.purchase.CheckoutGrpcRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.purchase.CheckoutGrpcRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.grpc.purchase.CheckoutGrpcRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.grpc.purchase.CheckoutGrpcRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.purchase.CheckoutGrpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.purchase.CheckoutGrpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.purchase.CheckoutGrpcRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code purchase.CheckoutGrpcRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:purchase.CheckoutGrpcRequest)
      com.example.grpc.purchase.CheckoutGrpcRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.purchase.PurchaseProto.internal_static_purchase_CheckoutGrpcRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.purchase.PurchaseProto.internal_static_purchase_CheckoutGrpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.purchase.CheckoutGrpcRequest.class, com.example.grpc.purchase.CheckoutGrpcRequest.Builder.class);
    }

    // Construct using com.example.grpc.purchase.CheckoutGrpcRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      touristId_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.purchase.PurchaseProto.internal_static_purchase_CheckoutGrpcRequest_descriptor;
    }

    @java.lang.Override
    public com.example.grpc.purchase.CheckoutGrpcRequest getDefaultInstanceForType() {
      return com.example.grpc.purchase.CheckoutGrpcRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.grpc.purchase.CheckoutGrpcRequest build() {
      com.example.grpc.purchase.CheckoutGrpcRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.grpc.purchase.CheckoutGrpcRequest buildPartial() {
      com.example.grpc.purchase.CheckoutGrpcRequest result = new com.example.grpc.purchase.CheckoutGrpcRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.grpc.purchase.CheckoutGrpcRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.touristId_ = touristId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.purchase.CheckoutGrpcRequest) {
        return mergeFrom((com.example.grpc.purchase.CheckoutGrpcRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.purchase.CheckoutGrpcRequest other) {
      if (other == com.example.grpc.purchase.CheckoutGrpcRequest.getDefaultInstance()) return this;
      if (other.getTouristId() != 0L) {
        setTouristId(other.getTouristId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              touristId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long touristId_ ;
    /**
     * <code>int64 tourist_id = 1;</code>
     * @return The touristId.
     */
    @java.lang.Override
    public long getTouristId() {
      return touristId_;
    }
    /**
     * <code>int64 tourist_id = 1;</code>
     * @param value The touristId to set.
     * @return This builder for chaining.
     */
    public Builder setTouristId(long value) {

      touristId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 tourist_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTouristId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      touristId_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:purchase.CheckoutGrpcRequest)
  }

  // @@protoc_insertion_point(class_scope:purchase.CheckoutGrpcRequest)
  private static final com.example.grpc.purchase.CheckoutGrpcRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.purchase.CheckoutGrpcRequest();
  }

  public static com.example.grpc.purchase.CheckoutGrpcRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckoutGrpcRequest>
      PARSER = new com.google.protobuf.AbstractParser<CheckoutGrpcRequest>() {
    @java.lang.Override
    public CheckoutGrpcRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CheckoutGrpcRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckoutGrpcRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.grpc.purchase.CheckoutGrpcRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

