// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: purchase/purchase.proto
// Protobuf Java Version: 4.34.1

package com.example.grpc.purchase;

/**
 * Protobuf type {@code purchase.CheckoutGrpcResponse}
 */
@com.google.protobuf.Generated
public final class CheckoutGrpcResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:purchase.CheckoutGrpcResponse)
    CheckoutGrpcResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "CheckoutGrpcResponse");
  }
  // Use CheckoutGrpcResponse.newBuilder() to construct.
  private CheckoutGrpcResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CheckoutGrpcResponse() {
    message_ = "";
    generatedTokens_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.purchase.PurchaseProto.internal_static_purchase_CheckoutGrpcResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.example.grpc.purchase.PurchaseProto.internal_static_purchase_CheckoutGrpcResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.purchase.PurchaseProto.internal_static_purchase_CheckoutGrpcResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.purchase.CheckoutGrpcResponse.class, com.example.grpc.purchase.CheckoutGrpcResponse.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_ = false;
  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENERATED_TOKENS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList generatedTokens_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string generated_tokens = 3;</code>
   * @return A list containing the generatedTokens.
   */
  public com.google.protobuf.ProtocolStringList
      getGeneratedTokensList() {
    return generatedTokens_;
  }
  /**
   * <code>repeated string generated_tokens = 3;</code>
   * @return The count of generatedTokens.
   */
  public int getGeneratedTokensCount() {
    return generatedTokens_.size();
  }
  /**
   * <code>repeated string generated_tokens = 3;</code>
   * @param index The index of the element to return.
   * @return The generatedTokens at the given index.
   */
  public java.lang.String getGeneratedTokens(int index) {
    return generatedTokens_.get(index);
  }
  /**
   * <code>repeated string generated_tokens = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the generatedTokens at the given index.
   */
  public com.google.protobuf.ByteString
      getGeneratedTokensBytes(int index) {
    return generatedTokens_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, message_);
    }
    for (int i = 0; i < generatedTokens_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, generatedTokens_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, message_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < generatedTokens_.size(); i++) {
        dataSize += computeStringSizeNoTag(generatedTokens_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getGeneratedTokensList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.purchase.CheckoutGrpcResponse)) {
      return super.equals(obj);
    }
    com.example.grpc.purchase.CheckoutGrpcResponse other = (com.example.grpc.purchase.CheckoutGrpcResponse) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getGeneratedTokensList()
        .equals(other.getGeneratedTokensList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getGeneratedTokensCount() > 0) {
      hash = (37 * hash) + GENERATED_TOKENS_FIELD_NUMBER;
      hash = (53 * hash) + getGeneratedTokensList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.purchase.CheckoutGrpcResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.purchase.CheckoutGrpcResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.purchase.CheckoutGrpcResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.purchase.CheckoutGrpcResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.purchase.CheckoutGrpcResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.purchase.CheckoutGrpcResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.purchase.CheckoutGrpcResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.purchase.CheckoutGrpcResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.grpc.purchase.CheckoutGrpcResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.grpc.purchase.CheckoutGrpcResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.purchase.CheckoutGrpcResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.purchase.CheckoutGrpcResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.purchase.CheckoutGrpcResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code purchase.CheckoutGrpcResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:purchase.CheckoutGrpcResponse)
      com.example.grpc.purchase.CheckoutGrpcResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.purchase.PurchaseProto.internal_static_purchase_CheckoutGrpcResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.purchase.PurchaseProto.internal_static_purchase_CheckoutGrpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.purchase.CheckoutGrpcResponse.class, com.example.grpc.purchase.CheckoutGrpcResponse.Builder.class);
    }

    // Construct using com.example.grpc.purchase.CheckoutGrpcResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      success_ = false;
      message_ = "";
      generatedTokens_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.purchase.PurchaseProto.internal_static_purchase_CheckoutGrpcResponse_descriptor;
    }

    @java.lang.Override
    public com.example.grpc.purchase.CheckoutGrpcResponse getDefaultInstanceForType() {
      return com.example.grpc.purchase.CheckoutGrpcResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.grpc.purchase.CheckoutGrpcResponse build() {
      com.example.grpc.purchase.CheckoutGrpcResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.grpc.purchase.CheckoutGrpcResponse buildPartial() {
      com.example.grpc.purchase.CheckoutGrpcResponse result = new com.example.grpc.purchase.CheckoutGrpcResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.grpc.purchase.CheckoutGrpcResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.success_ = success_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.message_ = message_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        generatedTokens_.makeImmutable();
        result.generatedTokens_ = generatedTokens_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.purchase.CheckoutGrpcResponse) {
        return mergeFrom((com.example.grpc.purchase.CheckoutGrpcResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.purchase.CheckoutGrpcResponse other) {
      if (other == com.example.grpc.purchase.CheckoutGrpcResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.generatedTokens_.isEmpty()) {
        if (generatedTokens_.isEmpty()) {
          generatedTokens_ = other.generatedTokens_;
          bitField0_ |= 0x00000004;
        } else {
          ensureGeneratedTokensIsMutable();
          generatedTokens_.addAll(other.generatedTokens_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              success_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              ensureGeneratedTokensIsMutable();
              generatedTokens_.add(input.readStringRequireUtf8());
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      success_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList generatedTokens_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureGeneratedTokensIsMutable() {
      if (!generatedTokens_.isModifiable()) {
        generatedTokens_ = new com.google.protobuf.LazyStringArrayList(generatedTokens_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string generated_tokens = 3;</code>
     * @return A list containing the generatedTokens.
     */
    public com.google.protobuf.ProtocolStringList
        getGeneratedTokensList() {
      generatedTokens_.makeImmutable();
      return generatedTokens_;
    }
    /**
     * <code>repeated string generated_tokens = 3;</code>
     * @return The count of generatedTokens.
     */
    public int getGeneratedTokensCount() {
      return generatedTokens_.size();
    }
    /**
     * <code>repeated string generated_tokens = 3;</code>
     * @param index The index of the element to return.
     * @return The generatedTokens at the given index.
     */
    public java.lang.String getGeneratedTokens(int index) {
      return generatedTokens_.get(index);
    }
    /**
     * <code>repeated string generated_tokens = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the generatedTokens at the given index.
     */
    public com.google.protobuf.ByteString
        getGeneratedTokensBytes(int index) {
      return generatedTokens_.getByteString(index);
    }
    /**
     * <code>repeated string generated_tokens = 3;</code>
     * @param index The index to set the value at.
     * @param value The generatedTokens to set.
     * @return This builder for chaining.
     */
    public Builder setGeneratedTokens(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureGeneratedTokensIsMutable();
      generatedTokens_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string generated_tokens = 3;</code>
     * @param value The generatedTokens to add.
     * @return This builder for chaining.
     */
    public Builder addGeneratedTokens(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureGeneratedTokensIsMutable();
      generatedTokens_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string generated_tokens = 3;</code>
     * @param values The generatedTokens to add.
     * @return This builder for chaining.
     */
    public Builder addAllGeneratedTokens(
        java.lang.Iterable<java.lang.String> values) {
      ensureGeneratedTokensIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, generatedTokens_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string generated_tokens = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGeneratedTokens() {
      generatedTokens_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string generated_tokens = 3;</code>
     * @param value The bytes of the generatedTokens to add.
     * @return This builder for chaining.
     */
    public Builder addGeneratedTokensBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureGeneratedTokensIsMutable();
      generatedTokens_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:purchase.CheckoutGrpcResponse)
  }

  // @@protoc_insertion_point(class_scope:purchase.CheckoutGrpcResponse)
  private static final com.example.grpc.purchase.CheckoutGrpcResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.purchase.CheckoutGrpcResponse();
  }

  public static com.example.grpc.purchase.CheckoutGrpcResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckoutGrpcResponse>
      PARSER = new com.google.protobuf.AbstractParser<CheckoutGrpcResponse>() {
    @java.lang.Override
    public CheckoutGrpcResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CheckoutGrpcResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckoutGrpcResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.grpc.purchase.CheckoutGrpcResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

