// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: purchase/purchase.proto
// Protobuf Java Version: 4.34.1

package com.example.grpc.purchase;

@com.google.protobuf.Generated
public interface CheckoutGrpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:purchase.CheckoutGrpcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 tourist_id = 1;</code>
   * @return The touristId.
   */
  long getTouristId();
}
