services:
  stakeholders-db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stakeholders_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stakeholders_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  blog-db:
    image: mongo:7
    command: mongod --quiet --logpath /dev/null
    volumes:
      - blog_mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=blogdb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123
    volumes:
      - ./config/servers.json:/pgadmin4/servers.json
      - ./config/pgpass:/tmp/pgpass
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - stakeholders-db

  stakeholders:
    build: ./stakeholders
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./stakeholders:/app
      - ./stakeholders/media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:root@stakeholders-db:5432/stakeholders_db
      - DEBUG=1
      - FOLLOWERS_SYNC_URL=http://followers:8081/api/followers/sync
    depends_on:
      stakeholders-db:
        condition: service_healthy
  blog:
    build: ./blog
    ports:
      - "3000:3000"
      - "50051:50051"
    environment:
      - MONGO_URI=mongodb://blog-db:27017/blogdb
      - JWT_SECRET=django-insecure-c7(b_d%7a&rz%tnm$5de3u8vb(4eoohvp0)_#^ii3wcm2m!t9p
    depends_on:
      blog-db:
        condition: service_healthy
  
  followers-db:
    image: neo4j:5.12
    ports:
      - "7474:7474" 
      - "7687:7687" 
    environment:
      - NEO4J_AUTH=neo4j/password123 
    volumes:
      - followers_data:/data
    healthcheck:
      test: ["CMD", "neo4j-admin", "server", "status"]
      interval: 5s
      timeout: 5s
      retries: 10

  tours-db:
    image: postgres:15
    volumes:
      - tours_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=tours_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tours_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  tours:
    build: ./tours
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=tours-db
      - DB_PORT=5432
      - DB_NAME=tours_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      tours-db:
        condition: service_healthy

  followers:
    build:
      context: .
      dockerfile: followers/demo/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_NEO4J_URI=bolt://followers-db:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=password123
    depends_on:
      followers-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  purchase-db:
    image: postgres:15
    volumes:
      - purchase_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=purchase_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d purchase_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  purchase:
    build:
      context: .
      dockerfile: purchase/Dockerfile
    ports:
      - "8083:8083"
      - "50054:50054"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://purchase-db:5432/purchase_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      purchase-db:
        condition: service_healthy

  gateway:
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=django-insecure-c7(b_d%7a&rz%tnm$5de3u8vb(4eoohvp0)_#^ii3wcm2m!t9p
    depends_on:
      - blog
      - stakeholders
      - followers
      - tours
      - purchase

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # dashboard
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  blog_mongo_data:
  pgadmin_data:
  media:
  followers_data:
  tours_postgres_data:
  purchase_postgres_data:

