[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         forward
    Listen       0.0.0.0
    Port         24224

[FILTER]
    Name         modify
    Match        microservice.*
    Condition    Key_Exists container_name
    Set          service_name $container_name

[OUTPUT]
    Name         loki
    Match        *
    Host         loki
    Port         3100
    Labels       job=fluent-bit
    Label_Keys   $service_name, $container_name