// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: purchase/purchase.proto

package purchase.grpc;

/**
 * Protobuf type {@code purchase.AddToCartGrpcRequest}
 */
public final class AddToCartGrpcRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:purchase.AddToCartGrpcRequest)
    AddToCartGrpcRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddToCartGrpcRequest.newBuilder() to construct.
  private AddToCartGrpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddToCartGrpcRequest() {
    touristId_ = "";
    tourId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AddToCartGrpcRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return purchase.grpc.PurchaseProto.internal_static_purchase_AddToCartGrpcRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return purchase.grpc.PurchaseProto.internal_static_purchase_AddToCartGrpcRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            purchase.grpc.AddToCartGrpcRequest.class, purchase.grpc.AddToCartGrpcRequest.Builder.class);
  }

  public static final int TOURIST_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object touristId_ = "";
  /**
   * <code>string tourist_id = 1;</code>
   * @return The touristId.
   */
  @java.lang.Override
  public java.lang.String getTouristId() {
    java.lang.Object ref = touristId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      touristId_ = s;
      return s;
    }
  }
  /**
   * <code>string tourist_id = 1;</code>
   * @return The bytes for touristId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTouristIdBytes() {
    java.lang.Object ref = touristId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      touristId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOUR_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tourId_ = "";
  /**
   * <code>string tour_id = 2;</code>
   * @return The tourId.
   */
  @java.lang.Override
  public java.lang.String getTourId() {
    java.lang.Object ref = tourId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tourId_ = s;
      return s;
    }
  }
  /**
   * <code>string tour_id = 2;</code>
   * @return The bytes for tourId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTourIdBytes() {
    java.lang.Object ref = tourId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tourId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(touristId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, touristId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tourId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tourId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(touristId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, touristId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tourId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tourId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof purchase.grpc.AddToCartGrpcRequest)) {
      return super.equals(obj);
    }
    purchase.grpc.AddToCartGrpcRequest other = (purchase.grpc.AddToCartGrpcRequest) obj;

    if (!getTouristId()
        .equals(other.getTouristId())) return false;
    if (!getTourId()
        .equals(other.getTourId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOURIST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTouristId().hashCode();
    hash = (37 * hash) + TOUR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTourId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static purchase.grpc.AddToCartGrpcRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static purchase.grpc.AddToCartGrpcRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static purchase.grpc.AddToCartGrpcRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static purchase.grpc.AddToCartGrpcRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static purchase.grpc.AddToCartGrpcRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static purchase.grpc.AddToCartGrpcRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static purchase.grpc.AddToCartGrpcRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static purchase.grpc.AddToCartGrpcRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static purchase.grpc.AddToCartGrpcRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static purchase.grpc.AddToCartGrpcRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static purchase.grpc.AddToCartGrpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static purchase.grpc.AddToCartGrpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(purchase.grpc.AddToCartGrpcRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code purchase.AddToCartGrpcRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:purchase.AddToCartGrpcRequest)
      purchase.grpc.AddToCartGrpcRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return purchase.grpc.PurchaseProto.internal_static_purchase_AddToCartGrpcRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return purchase.grpc.PurchaseProto.internal_static_purchase_AddToCartGrpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              purchase.grpc.AddToCartGrpcRequest.class, purchase.grpc.AddToCartGrpcRequest.Builder.class);
    }

    // Construct using purchase.grpc.AddToCartGrpcRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      touristId_ = "";
      tourId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return purchase.grpc.PurchaseProto.internal_static_purchase_AddToCartGrpcRequest_descriptor;
    }

    @java.lang.Override
    public purchase.grpc.AddToCartGrpcRequest getDefaultInstanceForType() {
      return purchase.grpc.AddToCartGrpcRequest.getDefaultInstance();
    }

    @java.lang.Override
    public purchase.grpc.AddToCartGrpcRequest build() {
      purchase.grpc.AddToCartGrpcRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public purchase.grpc.AddToCartGrpcRequest buildPartial() {
      purchase.grpc.AddToCartGrpcRequest result = new purchase.grpc.AddToCartGrpcRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(purchase.grpc.AddToCartGrpcRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.touristId_ = touristId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tourId_ = tourId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof purchase.grpc.AddToCartGrpcRequest) {
        return mergeFrom((purchase.grpc.AddToCartGrpcRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(purchase.grpc.AddToCartGrpcRequest other) {
      if (other == purchase.grpc.AddToCartGrpcRequest.getDefaultInstance()) return this;
      if (!other.getTouristId().isEmpty()) {
        touristId_ = other.touristId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTourId().isEmpty()) {
        tourId_ = other.tourId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              touristId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              tourId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object touristId_ = "";
    /**
     * <code>string tourist_id = 1;</code>
     * @return The touristId.
     */
    public java.lang.String getTouristId() {
      java.lang.Object ref = touristId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        touristId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tourist_id = 1;</code>
     * @return The bytes for touristId.
     */
    public com.google.protobuf.ByteString
        getTouristIdBytes() {
      java.lang.Object ref = touristId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        touristId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tourist_id = 1;</code>
     * @param value The touristId to set.
     * @return This builder for chaining.
     */
    public Builder setTouristId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      touristId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string tourist_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTouristId() {
      touristId_ = getDefaultInstance().getTouristId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string tourist_id = 1;</code>
     * @param value The bytes for touristId to set.
     * @return This builder for chaining.
     */
    public Builder setTouristIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      touristId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object tourId_ = "";
    /**
     * <code>string tour_id = 2;</code>
     * @return The tourId.
     */
    public java.lang.String getTourId() {
      java.lang.Object ref = tourId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tourId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tour_id = 2;</code>
     * @return The bytes for tourId.
     */
    public com.google.protobuf.ByteString
        getTourIdBytes() {
      java.lang.Object ref = tourId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tourId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tour_id = 2;</code>
     * @param value The tourId to set.
     * @return This builder for chaining.
     */
    public Builder setTourId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tourId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string tour_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTourId() {
      tourId_ = getDefaultInstance().getTourId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string tour_id = 2;</code>
     * @param value The bytes for tourId to set.
     * @return This builder for chaining.
     */
    public Builder setTourIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tourId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:purchase.AddToCartGrpcRequest)
  }

  // @@protoc_insertion_point(class_scope:purchase.AddToCartGrpcRequest)
  private static final purchase.grpc.AddToCartGrpcRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new purchase.grpc.AddToCartGrpcRequest();
  }

  public static purchase.grpc.AddToCartGrpcRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddToCartGrpcRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddToCartGrpcRequest>() {
    @java.lang.Override
    public AddToCartGrpcRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AddToCartGrpcRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddToCartGrpcRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public purchase.grpc.AddToCartGrpcRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

