// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: purchase/purchase.proto

package purchase.grpc;

public interface AddToCartGrpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:purchase.AddToCartGrpcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tourist_id = 1;</code>
   * @return The touristId.
   */
  java.lang.String getTouristId();
  /**
   * <code>string tourist_id = 1;</code>
   * @return The bytes for touristId.
   */
  com.google.protobuf.ByteString
      getTouristIdBytes();

  /**
   * <code>string tour_id = 2;</code>
   * @return The tourId.
   */
  java.lang.String getTourId();
  /**
   * <code>string tour_id = 2;</code>
   * @return The bytes for tourId.
   */
  com.google.protobuf.ByteString
      getTourIdBytes();
}
