// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: purchase/purchase.proto

package purchase.grpc;

public interface CheckoutGrpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:purchase.CheckoutGrpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated string generated_tokens = 3;</code>
   * @return A list containing the generatedTokens.
   */
  java.util.List<java.lang.String>
      getGeneratedTokensList();
  /**
   * <code>repeated string generated_tokens = 3;</code>
   * @return The count of generatedTokens.
   */
  int getGeneratedTokensCount();
  /**
   * <code>repeated string generated_tokens = 3;</code>
   * @param index The index of the element to return.
   * @return The generatedTokens at the given index.
   */
  java.lang.String getGeneratedTokens(int index);
  /**
   * <code>repeated string generated_tokens = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the generatedTokens at the given index.
   */
  com.google.protobuf.ByteString
      getGeneratedTokensBytes(int index);
}
