// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: purchase/purchase.proto

package purchase.grpc;

public interface CheckoutGrpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:purchase.CheckoutGrpcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tourist_id = 1;</code>
   * @return The touristId.
   */
  java.lang.String getTouristId();
  /**
   * <code>string tourist_id = 1;</code>
   * @return The bytes for touristId.
   */
  com.google.protobuf.ByteString
      getTouristIdBytes();
}
