// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: purchase/purchase.proto

package purchase.grpc;

public final class PurchaseProto {
  private PurchaseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_purchase_AddToCartGrpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_purchase_AddToCartGrpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_purchase_AddToCartGrpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_purchase_AddToCartGrpcResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_purchase_CheckoutGrpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_purchase_CheckoutGrpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_purchase_CheckoutGrpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_purchase_CheckoutGrpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027purchase/purchase.proto\022\010purchase\032\034goo" +
      "gle/api/annotations.proto\";\n\024AddToCartGr" +
      "pcRequest\022\022\n\ntourist_id\030\001 \001(\t\022\017\n\007tour_id" +
      "\030\002 \001(\t\"9\n\025AddToCartGrpcResponse\022\017\n\007succe" +
      "ss\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\")\n\023CheckoutGrp" +
      "cRequest\022\022\n\ntourist_id\030\001 \001(\t\"R\n\024Checkout" +
      "GrpcResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007message" +
      "\030\002 \001(\t\022\030\n\020generated_tokens\030\003 \003(\t2\356\001\n\017Pur" +
      "chaseService\022n\n\tAddToCart\022\036.purchase.Add" +
      "ToCartGrpcRequest\032\037.purchase.AddToCartGr" +
      "pcResponse\" \202\323\344\223\002\032\"\025/v1/purchase/cart/ad" +
      "d:\001*\022k\n\010Checkout\022\035.purchase.CheckoutGrpc" +
      "Request\032\036.purchase.CheckoutGrpcResponse\"" +
      " \202\323\344\223\002\032\"\025/v1/purchase/checkout:\001*B6\n\rpur" +
      "chase.grpcB\rPurchaseProtoP\001Z\024gateway/gen" +
      "/purchaseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_purchase_AddToCartGrpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_purchase_AddToCartGrpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_purchase_AddToCartGrpcRequest_descriptor,
        new java.lang.String[] { "TouristId", "TourId", });
    internal_static_purchase_AddToCartGrpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_purchase_AddToCartGrpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_purchase_AddToCartGrpcResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_purchase_CheckoutGrpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_purchase_CheckoutGrpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_purchase_CheckoutGrpcRequest_descriptor,
        new java.lang.String[] { "TouristId", });
    internal_static_purchase_CheckoutGrpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_purchase_CheckoutGrpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_purchase_CheckoutGrpcResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "GeneratedTokens", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
